// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechStore_BackEnd.Data;

#nullable disable

namespace TechStore_BackEnd.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TechStore_BackEnd.Models.Carrier", b =>
                {
                    b.Property<int>("Carrier_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("carrier_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Carrier_id"));

                    b.Property<string>("Carrier_description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("carrier_description");

                    b.Property<string>("Carrier_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("carrier_name");

                    b.HasKey("Carrier_id");

                    b.ToTable("Carriers");
                });

            modelBuilder.Entity("TechStore_BackEnd.Models.Shipment", b =>
                {
                    b.Property<int>("Shipment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shipment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Shipment_id"));

                    b.Property<int>("Carrier_id")
                        .HasColumnType("int")
                        .HasColumnName("carrier_id");

                    b.Property<DateOnly>("Shipment_arrival_date")
                        .HasColumnType("date")
                        .HasColumnName("shipment_arrival_date");

                    b.Property<DateOnly>("Shipment_order_date")
                        .HasColumnType("date")
                        .HasColumnName("shipment_order_date");

                    b.Property<double>("Shipment_price_usa")
                        .HasColumnType("double")
                        .HasColumnName("shipment_price_usa");

                    b.Property<double>("Shipment_weight_kg")
                        .HasColumnType("double")
                        .HasColumnName("shipment_weight_kg");

                    b.HasKey("Shipment_id");

                    b.HasIndex("Carrier_id");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("TechStore_BackEnd.Models.Shipment", b =>
                {
                    b.HasOne("TechStore_BackEnd.Models.Carrier", "Carrier")
                        .WithMany()
                        .HasForeignKey("Carrier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrier");
                });
#pragma warning restore 612, 618
        }
    }
}
